import {
    LayoutDashboard,
    Building2,
    BedDouble,
    ClipboardList,
    CalendarCheck,
    Users,
    Shield,
    Layers,
    Store,
    Shirt,
    ShoppingCart,
    UtensilsCrossed,
    Table2,
    Package,
    FileText,
    Utensils,
    Boxes,
    Warehouse,
    Bed,
} from "lucide-react";

export const SIDEBAR_ICON_MAP: Record<string, any> = {
    "/dashboard": LayoutDashboard,
    "/room-status": BedDouble,
    "/properties": Building2,
    "/bookings": CalendarCheck,
    "/rooms": Bed,
    "/roles": Shield,
    "/staff": Users,
    "/plans": Package,
    "/room-categories": Layers,
    "/vendors": Store,
    "/laundry-pricing": Shirt,
    "/laundry-orders": ClipboardList,
    "/enquiries": FileText,
    "/menu-items": UtensilsCrossed,
    "/orders": Utensils,
    "/restaurant-tables": Table2,
    "/kitchen-inventory": Package,
    "/inventory-master": Warehouse
};
