ALTER TABLE public.ref_vendors
ADD COLUMN IF NOT EXISTS bank_name VARCHAR(150),
ADD COLUMN IF NOT EXISTS account_holder_name VARCHAR(150),
ADD COLUMN IF NOT EXISTS account_number VARCHAR(50),
ADD COLUMN IF NOT EXISTS ifsc_code VARCHAR(20),
ADD COLUMN IF NOT EXISTS qr_code TEXT;

ALTER TABLE public.ref_vendors ALTER COLUMN qr_code TYPE TEXT;
